package model

type WorksImage struct {
	Src string `json:"src"`
	Alt string `json:"alt"`
}

type WorksData struct {
	WorksData []Work `json:"worksData"`
}

type Work struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Category    string       `json:"category"`
	Images      []WorksImage `json:"image"`
	Href        string       `json:"href"`
	Description string       `json:"description"`
	Sold        bool         `json:"sold"`
}

func GetWorksData() WorksData {
	return WorksData{
		WorksData: []Work{
			{
				ID: "NoName 01",
				// Title:    "NoName 01",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/1/IMG_5353.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5354.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5355.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5356.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5357.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5358.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5359.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5360.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5361.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5362.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5363.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5364.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5365.jpg", Alt: "NoName 01"},
				},
				Href:        "/works/turnables/noname01",
				Description: "1990 - Rotation loop area 1,70m",
				Sold:        true,
			},
			{
				ID: "NoName 02",
				// Title:    "NoName 02",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/2/IMG_5366.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5367.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5368.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5369.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5370.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5371.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5372.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5373.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5374.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5375.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5376.jpg", Alt: "NoName 02"},
				},
				Href:        "/works/turnables/noname02",
				Description: "1990 - Rotation loop area 2,60m; Frame 1,54m x 1,57m",
				Sold:        false,
			},
			{
				ID: "NoName 03",
				// Title:    "NoName 03",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/3/IMG_5378.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5379.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5380.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5381.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5382.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5383.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5384.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5385.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5386.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5387.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5388.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5389.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5390.jpg", Alt: "NoName 03"},
				},
				Href:        "/works/turnables/noname03",
				Description: "1990 - Rotation loop area 1m",
				Sold:        true,
			},
			{
				ID: "NoName 04",
				// Title:    "NoName 04",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/4/IMG_5391.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5392.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5393.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5394.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5395.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5396.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5397.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5398.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5399.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5400.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5401.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5402.jpg", Alt: "NoName 04"},
				},
				Href:        "/works/turnables/noname04",
				Description: "1990 - Rotation loop area 1,70m",
				Sold:        true,
			},
			{
				ID: "NoName 05",
				// Title:    "NoName 05",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/5/IMG_5404.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5405.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5406.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5407.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5408.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5409.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5410.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5411.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5412.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5413.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5414.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5415.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5416.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5417.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5418.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5419.jpg", Alt: "NoName 05"},
				},
				Href:        "/works/turnables/noname05",
				Description: "1990 - Rotation loop area 0,76m",
				Sold:        true,
			},
			{
				ID:       "actio-reactio",
				Title:    "Actio reactio",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-1.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-2.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-3.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-4.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-5.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-6.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-7.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-8.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-9.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-10.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-11.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-12.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-13.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-14.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-15.jpg", Alt: "Actio reactio"},
				},
				Href:        "/works/turnables/actio-reactio",
				Description: "1993 - Rotation loop area 4,30m x 2,80m",
				Sold:        false,
			},
			{
				ID:       "jacinta",
				Title:    "Jacinta",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/jacinta/IMG_5558.jpg", Alt: "Jacinta 01"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5559.jpg", Alt: "Jacinta 02"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5560.jpg", Alt: "Jacinta 03"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5561.jpg", Alt: "Jacinta 04"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5562.jpg", Alt: "Jacinta 05"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5563.jpg", Alt: "Jacinta 06"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5564.jpg", Alt: "Jacinta 07"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5565.jpg", Alt: "Jacinta 08"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5566.jpg", Alt: "Jacinta 09"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5567.jpg", Alt: "Jacinta 10"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5568.jpg", Alt: "Jacinta 11"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5569.jpg", Alt: "Jacinta 12"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5570.jpg", Alt: "Jacinta 15"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5571.jpg", Alt: "Jacinta 15"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5572.jpg", Alt: "Jacinta 15"},
				},
				Href:        "/works/turnables/jacinta",
				Description: "\"Jacinta\" rotation loop area    0,76 - 1995",
				Sold:        false,
			},
			{
				ID:          "b001",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b001.jpg", Alt: ""}},
				Href:        "/works/pictures/b001",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b002",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b002.jpg", Alt: ""}},
				Href:        "/works/pictures/b002",
				Description: "",
				Sold:        false,
			},
			{
				ID:       "jaiba-coja",
				Title:    "Jaiba Coja",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5594.jpg", Alt: "Jaiba coja 01"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5595.jpg", Alt: "Jaiba coja 02"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5596.jpg", Alt: "Jaiba coja 03"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5597.jpg", Alt: "Jaiba coja 04"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5598.jpg", Alt: "Jaiba coja 05"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5599.jpg", Alt: "Jaiba coja 06"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5600.jpg", Alt: "Jaiba coja 07"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5601.jpg", Alt: "Jaiba coja 08"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5602.jpg", Alt: "Jaiba coja 09"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5603.jpg", Alt: "Jaiba coja 10"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5604.jpg", Alt: "Jaiba coja 11"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5605.jpg", Alt: "Jaiba coja 12"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5606.jpg", Alt: "Jaiba coja 13"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5607.jpg", Alt: "Jaiba coja 14"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5608.jpg", Alt: "Jaiba coja 15"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5609.jpg", Alt: "Jaiba coja 16"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5610.jpg", Alt: "Jaiba coja 17"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5611.jpg", Alt: "Jaiba coja 18"},
				},
				Href:        "/works/turnables/jaiba-coja",
				Description: "\"Jaiba coja\" rotation loop area    0,68 - 1996",
				Sold:        false,
			},
			{
				ID: "NoName 18",
				// Title:    "NoName 18",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/18/IMG_5585.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5586.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5587.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5588.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5589.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5590.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5591.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5592.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5593.jpg", Alt: "NoName 18"},
				},
				Href:        "/works/turnables/noname18",
				Description: "1996 - 1,65m x 3,07m, rotation loop area each 1,65m",
				Sold:        true,
			},
			{
				ID:          "b003",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b003.jpg", Alt: ""}},
				Href:        "/works/pictures/b003",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b004",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b004.jpg", Alt: ""}},
				Href:        "/works/pictures/b004",
				Description: "",
				Sold:        false,
			},

			{
				ID:          "b005",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b005.jpg", Alt: ""}},
				Href:        "/works/pictures/b005",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b006",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b006.jpg", Alt: ""}},
				Href:        "/works/pictures/b006",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b007",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b007.jpg", Alt: ""}},
				Href:        "/works/pictures/b007",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b008",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b008.jpg", Alt: ""}},
				Href:        "/works/pictures/b008",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b009",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b009.jpg", Alt: ""}},
				Href:        "/works/pictures/b009",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b010",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b010.jpg", Alt: ""}},
				Href:        "/works/pictures/b010",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b011",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b011.jpg", Alt: ""}},
				Href:        "/works/pictures/b011",
				Description: "",
				Sold:        false,
			},

			{
				ID:          "b012",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b012.jpg", Alt: ""}},
				Href:        "/works/pictures/b012",
				Description: "",
				Sold:        false,
			},

			{
				ID:          "b013",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b013.jpg", Alt: ""}},
				Href:        "/works/pictures/b013",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b014",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b014.jpg", Alt: ""}},
				Href:        "/works/pictures/b014",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b015",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b015.jpg", Alt: ""}},
				Href:        "/works/pictures/b015",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b016",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b016.jpg", Alt: ""}},
				Href:        "/works/pictures/b016",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b017",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b017.jpg", Alt: ""}},
				Href:        "/works/pictures/b017",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b018",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b018.jpg", Alt: ""}},
				Href:        "/works/pictures/b018",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b019",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b019.jpg", Alt: ""}},
				Href:        "/works/pictures/b019",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b020",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b020.jpg", Alt: ""}},
				Href:        "/works/pictures/b020",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b021",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b021.jpg", Alt: ""}},
				Href:        "/works/pictures/b021",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b023",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b023.jpg", Alt: ""}},
				Href:        "/works/pictures/b023",
				Description: "",
				Sold:        false,
			},
		},
	}
}
