package model

type WorksImage struct {
	Src string `json:"src"`
	Alt string `json:"alt"`
}

type WorksData struct {
	WorksData []Work `json:"worksData"`
}

type Work struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Category    string       `json:"category"`
	Images      []WorksImage `json:"image"`
	Href        string       `json:"href"`
	Description string       `json:"description"`
	Sold        bool         `json:"sold"`
}

func GetWorksData() WorksData {
	return WorksData{
		WorksData: []Work{
			{
				ID: "NoName 01",
				// Title:    "NoName 01",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/1/IMG_5353.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5354.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5355.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5356.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5357.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5358.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5359.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5360.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5361.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5362.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5363.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5364.jpg", Alt: "NoName 01"},
					{Src: "/static/images/works/turnables/1/IMG_5365.jpg", Alt: "NoName 01"},
				},
				Href:        "/works/turnables/noname01",
				Description: "1990 - Rotation loop area 1,70m",
				Sold:        true,
			},
			{
				ID: "NoName 02",
				// Title:    "NoName 02",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/2/IMG_5366.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5367.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5368.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5369.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5370.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5371.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5372.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5373.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5374.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5375.jpg", Alt: "NoName 02"},
					{Src: "/static/images/works/turnables/2/IMG_5376.jpg", Alt: "NoName 02"},
				},
				Href:        "/works/turnables/noname02",
				Description: "1990 - Rotation loop area 2,60m; Frame 1,54m x 1,57m",
				Sold:        false,
			},
			{
				ID: "NoName 03",
				// Title:    "NoName 03",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/3/IMG_5378.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5379.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5380.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5381.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5382.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5383.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5384.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5385.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5386.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5387.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5388.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5389.jpg", Alt: "NoName 03"},
					{Src: "/static/images/works/turnables/3/IMG_5390.jpg", Alt: "NoName 03"},
				},
				Href:        "/works/turnables/noname03",
				Description: "1990 - Rotation loop area 1m",
				Sold:        true,
			},
			{
				ID: "NoName 04",
				// Title:    "NoName 04",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/4/IMG_5391.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5392.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5393.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5394.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5395.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5396.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5397.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5398.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5399.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5400.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5401.jpg", Alt: "NoName 04"},
					{Src: "/static/images/works/turnables/4/IMG_5402.jpg", Alt: "NoName 04"},
				},
				Href:        "/works/turnables/noname04",
				Description: "1990 - Rotation loop area 1,70m",
				Sold:        true,
			},
			{
				ID: "NoName 05",
				// Title:    "NoName 05",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/5/IMG_5404.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5405.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5406.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5407.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5408.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5409.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5410.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5411.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5412.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5413.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5414.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5415.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5416.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5417.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5418.jpg", Alt: "NoName 05"},
					{Src: "/static/images/works/turnables/5/IMG_5419.jpg", Alt: "NoName 05"},
				},
				Href:        "/works/turnables/noname05",
				Description: "1990 - Rotation loop area 0,76m",
				Sold:        true,
			},
			{
				ID: "NoName 6",
				// Title:    "NoName 06",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/6/IMG_5420.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5421.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5422.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5423.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5424.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5426.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5427.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5428.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5429.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5430.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5431.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5432.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5433.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5434.jpg", Alt: "NoName 06"},
					{Src: "/static/images/works/turnables/6/IMG_5435.jpg", Alt: "NoName 06"},
				},
				Href:        "/works/turnables/noname06",
				Description: "1991 - Rotation loop area 1,60m",
				Sold:        true,
			},
			{
				ID: "NoName 7",
				// Title:    "NoName 07",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/7/IMG_5436.jpg", Alt: "NoName 07"},
					{Src: "/static/images/works/turnables/7/IMG_5437.jpg", Alt: "NoName 07"},
					{Src: "/static/images/works/turnables/7/IMG_5438.jpg", Alt: "NoName 07"},
					{Src: "/static/images/works/turnables/7/IMG_5439.jpg", Alt: "NoName 07"},
					{Src: "/static/images/works/turnables/7/IMG_5440.jpg", Alt: "NoName 07"},
					{Src: "/static/images/works/turnables/7/IMG_5442.jpg", Alt: "NoName 07"},
					{Src: "/static/images/works/turnables/7/IMG_5443.jpg", Alt: "NoName 07"},
					{Src: "/static/images/works/turnables/7/IMG_5444.jpg", Alt: "NoName 07"},
				},
				Href:        "/works/turnables/noname07",
				Description: "1991 - Rotation loop area 3m",
				Sold:        true,
			},
			{
				ID: "NoName 15",
				// Title:    "NoName 015",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/15/IMG_5548.jpg", Alt: "NoName 015"},
					{Src: "/static/images/works/turnables/15/IMG_5549.jpg", Alt: "NoName 015"},
					{Src: "/static/images/works/turnables/15/IMG_5550.jpg", Alt: "NoName 015"},
					{Src: "/static/images/works/turnables/15/IMG_5551.jpg", Alt: "NoName 015"},
					{Src: "/static/images/works/turnables/15/IMG_5552.jpg", Alt: "NoName 015"},
					{Src: "/static/images/works/turnables/15/IMG_5554.jpg", Alt: "NoName 015"},
					{Src: "/static/images/works/turnables/15/IMG_5555.jpg", Alt: "NoName 015"},
					{Src: "/static/images/works/turnables/15/IMG_5556.jpg", Alt: "NoName 015"},
					{Src: "/static/images/works/turnables/15/IMG_5557.jpg", Alt: "NoName 015"},
				},
				Href:        "/works/turnables/noname015",
				Description: "1995 - Rotation loop area 1m\nDistance between the axles 1,92m",
				Sold:        true,
			},
			{
				ID: "NoName 17",
				// Title:    "NoName 017",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/17/IMG_5573.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5574.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5575.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5576.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5577.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5579.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5580.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5581.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5582.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5583.jpg", Alt: "NoName 017"},
					{Src: "/static/images/works/turnables/17/IMG_5584.jpg", Alt: "NoName 017"},
				},
				Href:        "/works/turnables/noname017",
				Description: "1996",
				Sold:        true,
			},
			{
				ID:       "kakadu",
				Title:    "kakadu",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/kakadu/IMG_5639.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5640.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5641.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5642.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5643.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5644.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5645.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5646.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5647.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5648.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5649.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5650.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5651.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5652.jpg", Alt: "Kakadu"},
					{Src: "/static/images/works/turnables/kakadu/IMG_5653.jpg", Alt: "Kakadu"},
				},
				Href:        "/works/turnables/kakadu",
				Description: "1990 - Rotation loop area 0,76m",
				Sold:        true,
			},
			{
				ID:       "die-zwei-jacos",
				Title:    "Die zwei Jacos",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5499.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5500.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5501.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5502.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5503.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5504.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5505.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5506.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5507.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5508.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5509.jpg", Alt: "Die zwie Jacos"},
					{Src: "/static/images/works/turnables/die-zwei-jacos/IMG_5510.jpg", Alt: "Die zwie Jacos"},
				},
				Href:        "/works/turnables/die-zwei-jacos",
				Description: "1994 - Rotation loop area 1,31m x 1,32m",
				Sold:        true,
			},
			{
				ID:       "actio-reactio",
				Title:    "Actio reactio",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-1.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-2.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-3.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-4.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-5.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-6.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-7.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-8.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-9.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-10.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-11.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-12.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-13.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-14.jpg", Alt: "Actio reactio"},
					{Src: "/static/images/works/turnables/actio-reactio/actio-reactio-15.jpg", Alt: "Actio reactio"},
				},
				Href:        "/works/turnables/actio-reactio",
				Description: "1993 - Rotation loop area 4,30m x 2,80m",
				Sold:        false,
			},
			{
				ID:       "jacinta",
				Title:    "Jacinta",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/jacinta/IMG_5558.jpg", Alt: "Jacinta 01"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5559.jpg", Alt: "Jacinta 02"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5560.jpg", Alt: "Jacinta 03"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5561.jpg", Alt: "Jacinta 04"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5562.jpg", Alt: "Jacinta 05"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5563.jpg", Alt: "Jacinta 06"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5564.jpg", Alt: "Jacinta 07"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5565.jpg", Alt: "Jacinta 08"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5566.jpg", Alt: "Jacinta 09"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5567.jpg", Alt: "Jacinta 10"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5568.jpg", Alt: "Jacinta 11"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5569.jpg", Alt: "Jacinta 12"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5570.jpg", Alt: "Jacinta 15"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5571.jpg", Alt: "Jacinta 15"},
					{Src: "/static/images/works/turnables/jacinta/IMG_5572.jpg", Alt: "Jacinta 15"},
				},
				Href:        "/works/turnables/jacinta",
				Description: "\"Jacinta\" rotation loop area    0,76 - 1995",
				Sold:        false,
			},
			{
				ID:       "feuermuehle",
				Title:    "Feuermühle",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5624.jpg", Alt: "Feuermühle 01"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5625.jpg", Alt: "Feuermühle 02"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5626.jpg", Alt: "Feuermühle 03"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5627.jpg", Alt: "Feuermühle 04"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5628.jpg", Alt: "Feuermühle 05"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5629.jpg", Alt: "Feuermühle 06"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5630.jpg", Alt: "Feuermühle 07"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5631.jpg", Alt: "Feuermühle 08"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5632.jpg", Alt: "Feuermühle 09"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5633.jpg", Alt: "Feuermühle 10"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5634.jpg", Alt: "Feuermühle 11"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5635.jpg", Alt: "Feuermühle 12"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5636.jpg", Alt: "Feuermühle 15"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5637.jpg", Alt: "Feuermühle 15"},
					{Src: "/static/images/works/turnables/feuermuehle/IMG_5638.jpg", Alt: "Feuermühle 15"},
				},
				Href:        "/works/turnables/feuermuehle",
				Description: "\"Feuermühle\" rotation loop area    1,04m - 1997",
				Sold:        true,
			},
			{
				ID:          "b001",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b001.jpg", Alt: ""}},
				Href:        "/works/pictures/b001",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b002",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b002.jpg", Alt: ""}},
				Href:        "/works/pictures/b002",
				Description: "",
				Sold:        false,
			},
			{
				ID:       "jaiba-coja",
				Title:    "Jaiba Coja",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5594.jpg", Alt: "Jaiba coja 01"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5595.jpg", Alt: "Jaiba coja 02"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5596.jpg", Alt: "Jaiba coja 03"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5597.jpg", Alt: "Jaiba coja 04"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5598.jpg", Alt: "Jaiba coja 05"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5599.jpg", Alt: "Jaiba coja 06"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5600.jpg", Alt: "Jaiba coja 07"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5601.jpg", Alt: "Jaiba coja 08"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5602.jpg", Alt: "Jaiba coja 09"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5603.jpg", Alt: "Jaiba coja 10"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5604.jpg", Alt: "Jaiba coja 11"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5605.jpg", Alt: "Jaiba coja 12"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5606.jpg", Alt: "Jaiba coja 13"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5607.jpg", Alt: "Jaiba coja 14"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5608.jpg", Alt: "Jaiba coja 15"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5609.jpg", Alt: "Jaiba coja 16"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5610.jpg", Alt: "Jaiba coja 17"},
					{Src: "/static/images/works/turnables/jaiba-coja/IMG_5611.jpg", Alt: "Jaiba coja 18"},
				},
				Href:        "/works/turnables/jaiba-coja",
				Description: "\"Jaiba coja\" rotation loop area    0,68 - 1996",
				Sold:        false,
			},
			{
				ID:       "follow-me-i-follow-you",
				Title:    "Follow me, I follow you",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5511.jpg", Alt: "Follow me, I follow you 01"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5512.jpg", Alt: "Follow me, I follow you 02"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5513.jpg", Alt: "Follow me, I follow you 03"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5514.jpg", Alt: "Follow me, I follow you 04"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5515.jpg", Alt: "Follow me, I follow you 05"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5516.jpg", Alt: "Follow me, I follow you 06"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5517.jpg", Alt: "Follow me, I follow you 07"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5518.jpg", Alt: "Follow me, I follow you 08"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5519.jpg", Alt: "Follow me, I follow you 09"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5520.jpg", Alt: "Follow me, I follow you 10"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5521.jpg", Alt: "Follow me, I follow you 11"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5522.jpg", Alt: "Follow me, I follow you 12"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5523.jpg", Alt: "Follow me, I follow you 13"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5524.jpg", Alt: "Follow me, I follow you 14"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5525.jpg", Alt: "Follow me, I follow you 15"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5526.jpg", Alt: "Follow me, I follow you 16"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5527.jpg", Alt: "Follow me, I follow you 17"},
					{Src: "/static/images/works/turnables/follow-me-i-follow-you/IMG_5528.jpg", Alt: "Follow me, I follow you 18"},
				},
				Href:        "/works/turnables/follow-me-i-follow-you",
				Description: "\"Follow me, I follow you\" - 1995\nRotation loop area 1,34m & 1,36m\nDistance between the axles 1,17m",
				Sold:        true,
			},
			{
				ID:       "tourteaux-tourneurs",
				Title:    "Tourteaux tourneurs",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5529.jpg", Alt: "Tourteaux tourneurs 01"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5530.jpg", Alt: "Tourteaux tourneurs 02"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5531.jpg", Alt: "Tourteaux tourneurs 03"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5532.jpg", Alt: "Tourteaux tourneurs 04"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5533.jpg", Alt: "Tourteaux tourneurs 05"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5534.jpg", Alt: "Tourteaux tourneurs 06"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5535.jpg", Alt: "Tourteaux tourneurs 07"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5536.jpg", Alt: "Tourteaux tourneurs 08"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5537.jpg", Alt: "Tourteaux tourneurs 09"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5538.jpg", Alt: "Tourteaux tourneurs 10"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5539.jpg", Alt: "Tourteaux tourneurs 11"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5540.jpg", Alt: "Tourteaux tourneurs 12"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5541.jpg", Alt: "Tourteaux tourneurs 13"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5542.jpg", Alt: "Tourteaux tourneurs 14"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5543.jpg", Alt: "Tourteaux tourneurs 15"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5544.jpg", Alt: "Tourteaux tourneurs 16"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5545.jpg", Alt: "Tourteaux tourneurs 17"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5546.jpg", Alt: "Tourteaux tourneurs 18"},
					{Src: "/static/images/works/turnables/tourteaux-tourneurs/IMG_5547.jpg", Alt: "Tourteaux tourneurs 19"},
				},
				Href:        "/works/turnables/tourteaux-tourneurs",
				Description: "\"Tourteaux tourneurs\" rotation loop area 1,80m each\nDistance between the axles 3,20m",
				Sold:        true,
			},
			{
				ID:       "sapo-guapo",
				Title:    "Sapo guapo",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5612.jpg", Alt: "Sapo guapo 01"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5613.jpg", Alt: "Sapo guapo 02"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5614.jpg", Alt: "Sapo guapo 03"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5615.jpg", Alt: "Sapo guapo 04"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5616.jpg", Alt: "Sapo guapo 05"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5617.jpg", Alt: "Sapo guapo 06"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5618.jpg", Alt: "Sapo guapo 07"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5619.jpg", Alt: "Sapo guapo 08"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5620.jpg", Alt: "Sapo guapo 09"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5621.jpg", Alt: "Sapo guapo 10"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5622.jpg", Alt: "Sapo guapo 11"},
					{Src: "/static/images/works/turnables/sapo-guapo/IMG_5623.jpg", Alt: "Sapo guapo 12"},
				},
				Href:        "/works/turnables/sapo-guapo",
				Description: "\"Sapo guapo\" rotation loop area    0,74 - 1996",
				Sold:        false,
			},
			{
				ID:       "backturm",
				Title:    "Backturm",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/backturm/IMG_5479.jpg", Alt: "Backturm 01"},
					{Src: "/static/images/works/turnables/backturm/IMG_5480.jpg", Alt: "Backturm 02"},
					{Src: "/static/images/works/turnables/backturm/IMG_5481.jpg", Alt: "Backturm 03"},
					{Src: "/static/images/works/turnables/backturm/IMG_5482.jpg", Alt: "Backturm 04"},
					{Src: "/static/images/works/turnables/backturm/IMG_5483.jpg", Alt: "Backturm 05"},
					{Src: "/static/images/works/turnables/backturm/IMG_5484.jpg", Alt: "Backturm 06"},
					{Src: "/static/images/works/turnables/backturm/IMG_5485.jpg", Alt: "Backturm 07"},
					{Src: "/static/images/works/turnables/backturm/IMG_5486.jpg", Alt: "Backturm 08"},
					{Src: "/static/images/works/turnables/backturm/IMG_5487.jpg", Alt: "Backturm 09"},
					{Src: "/static/images/works/turnables/backturm/IMG_5488.jpg", Alt: "Backturm 10"},
					{Src: "/static/images/works/turnables/backturm/IMG_5489.jpg", Alt: "Backturm 11"},
				},
				Href:        "/works/turnables/Backturm",
				Description: "\"Backturm\" 1,17m x 1,17m - 1993",
				Sold:        true,
			},
			{
				ID:       "l'oiseau-fugueur",
				Title:    "L'oiseau fugueur",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5490.jpg", Alt: "L'oiseau fugueur 01"},
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5491.jpg", Alt: "L'oiseau fugueur 02"},
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5492.jpg", Alt: "L'oiseau fugueur 03"},
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5493.jpg", Alt: "L'oiseau fugueur 04"},
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5494.jpg", Alt: "L'oiseau fugueur 05"},
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5495.jpg", Alt: "L'oiseau fugueur 06"},
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5496.jpg", Alt: "L'oiseau fugueur 07"},
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5497.jpg", Alt: "L'oiseau fugueur 08"},
					{Src: "/static/images/works/turnables/loiseau-fugueur/IMG_5498.jpg", Alt: "L'oiseau fugueur 09"},
				},
				Href:        "/works/turnables/loiseau-fugueur",
				Description: "\"L'oiseau fugueur\" rotation loop area    1,30 - 1994",
				Sold:        true,
			},
			{
				ID: "NoName 18",
				// Title:    "NoName 18",
				Category: "turnables",
				Images: []WorksImage{
					{Src: "/static/images/works/turnables/18/IMG_5585.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5586.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5587.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5588.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5589.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5590.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5591.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5592.jpg", Alt: "NoName 18"},
					{Src: "/static/images/works/turnables/18/IMG_5593.jpg", Alt: "NoName 18"},
				},
				Href:        "/works/turnables/noname18",
				Description: "1996 - 1,65m x 3,07m, rotation loop area each 1,65m",
				Sold:        true,
			},
			{
				ID:          "b003",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b003.jpg", Alt: ""}},
				Href:        "/works/pictures/b003",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b004",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b004.jpg", Alt: ""}},
				Href:        "/works/pictures/b004",
				Description: "",
				Sold:        false,
			},

			{
				ID:          "b005",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b005.jpg", Alt: ""}},
				Href:        "/works/pictures/b005",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b006",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b006.jpg", Alt: ""}},
				Href:        "/works/pictures/b006",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b007",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b007.jpg", Alt: ""}},
				Href:        "/works/pictures/b007",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b008",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b008.jpg", Alt: ""}},
				Href:        "/works/pictures/b008",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b009",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b009.jpg", Alt: ""}},
				Href:        "/works/pictures/b009",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b010",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b010.jpg", Alt: ""}},
				Href:        "/works/pictures/b010",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b011",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b011.jpg", Alt: ""}},
				Href:        "/works/pictures/b011",
				Description: "",
				Sold:        false,
			},

			{
				ID:          "b012",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b012.jpg", Alt: ""}},
				Href:        "/works/pictures/b012",
				Description: "",
				Sold:        false,
			},

			{
				ID:          "b013",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b013.jpg", Alt: ""}},
				Href:        "/works/pictures/b013",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b014",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b014.jpg", Alt: ""}},
				Href:        "/works/pictures/b014",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b015",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b015.jpg", Alt: ""}},
				Href:        "/works/pictures/b015",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b016",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b016.jpg", Alt: ""}},
				Href:        "/works/pictures/b016",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b017",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b017.jpg", Alt: ""}},
				Href:        "/works/pictures/b017",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b018",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b018.jpg", Alt: ""}},
				Href:        "/works/pictures/b018",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b019",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b019.jpg", Alt: ""}},
				Href:        "/works/pictures/b019",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b020",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b020.jpg", Alt: ""}},
				Href:        "/works/pictures/b020",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b021",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b021.jpg", Alt: ""}},
				Href:        "/works/pictures/b021",
				Description: "",
				Sold:        false,
			},
			{
				ID:          "b023",
				Title:       "",
				Category:    "pictures",
				Images:      []WorksImage{{Src: "/static/images/works/pictures/b023.jpg", Alt: ""}},
				Href:        "/works/pictures/b023",
				Description: "",
				Sold:        false,
			},
		},
	}
}
